[config.wallpaper]
command = "swww"
# arguments = ["img", "--transition-type", "center"]
set = false


[templates.waybar]
input_path = './templates/colors.css'
output_path = '~/.dotfiles/themes/tokyonight-dark/dot-config/waybar/colors.css'
# post_hook = 'sleep 0.5; pkill -SIGUSR2 waybar'

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/matugen-colors.conf'
post_hook = 'hyprctl reload'

[templates.rofi]
input_path = './templates/rofi-colors.rasi'
output_path = '~/.dotfiles/test-matugen/dot-config/rofi/colors.rasi'

# [templates.kitty]
# input_path = 'templates/kitty-colors.conf'
# output_path = '~/.config/kitty/colors.conf'
# post_hook = 'kill -SIGUSR1 (pgrep kitty)'

[templates.vesktop]
input_path = 'templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/matugen.css'

# [templates.gtk3]
# input_path = 'templates/gtk-colors.css'
# output_path = '~/.dotfiles/test-matugen/dot-config/gtk-3.0/colors.css'
# post_hook = "~/.config/matugen/scripts/gtk.fish {{mode}}"

# [templates.gtk4]
# input_path = 'templates/gtk-colors.css'
# output_path = '~/.dotfiles/test-matugen/dot-config/gtk-4.0/colors.css'

# [templates.starship]
# input_path = 'templates/starship-colors.toml'
# output_path = '~/.config/starship.toml'

[templates.btop]
input_path = 'templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'

# [templates.zellij]
# input_path = 'templates/zellij.kdl'
# output_path = '~/.config/zellij/themes/matugen.kdl'

# [templates.zen]
# input_path = 'templates/zen-colors.css'
# output_path = '~/.zen/8g91a1lm.Default Profile/chrome/colors.css'
