hl.on("hyprland.start", function()
    hl.exec_cmd("waypaper --restore --no-post-command")
    hl.exec_cmd("waybar")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 28")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("opencloud")
end)
