-- local full_screen = 191
--
-- -- default status column, simply 2 spaces
-- local statuscolumn = "%l "
-- -- status column if only one buffer is open
-- -- (full_screen - text width) / 2
-- local statuscolumn_wide = string.rep(" ", (full_screen - 100) / 2) .. statuscolumn
--
-- -- set default
-- vim.o.statuscolumn = statuscolumn
--
-- -- check window list count and adapt padding
-- vim.api.nvim_create_autocmd({
--     'BufEnter', 'BufWinEnter', 'BufWinLeave', 'WinEnter', 'WinLeave', 'WinResized', 'VimResized'
-- }, {
--   callback = function()
--       local winwidth = vim.api.nvim_win_get_width(0)
--       if winwidth > (full_screen / 2) then
--         vim.o.statuscolumn = statuscolumn_wide
--       else
--         vim.o.statuscolumn = statuscolumn
--       end
--   end,
-- })
