# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/yzwxdfc7823bxlncfyj978mzh6pqw3xj-hm-session-vars.fish

set -g fish_greeting ""
fish_add_path -a /home/evolve/.local/bin

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add --position anywhere -- bh '| bat -phelp'
    abbr --add -- br 'git branch'
    abbr --add -- dc 'docker compose'
    abbr --add -- g git
    abbr --add -- gcm 'git commit -m "'
    abbr --add -- gm 'git merge'
    abbr --add -- grb 'git rebase'
    abbr --add -- gs 'git status -s'
    abbr --add -- gss 'git status'
    abbr --add -- ls lsd
    abbr --add -- n nvim
    abbr --add -- nl 'hyprshade toggle bluefilter'
    abbr --add -- nl0 'hyprshade off'
    abbr --add -- nl2 'hyprshade toggle blue-light-filter'
    abbr --add -- nr 'nix run nixpkgs#'
    abbr --add -- ns 'nix shell nixpkgs#'
    abbr --add -- nv nvim
    abbr --add -- ph 'git push'
    abbr --add -- pl 'git pull'
    abbr --add -- rm 'trash put'
    abbr --add -- sv 'sudo -e'
    abbr --add -- sw 'git switch'
    abbr --add -- v nvim

    # Aliases

    # Interactive shell initialisation
    fish_vi_key_bindings
    # zellij -l welcome
    # if test "$TERM" = "xterm-kitty" -a -z "$ZELLIJ"
    #   exec zellij --layout welcome
    # end

    direnv hook fish | source

    /nix/store/48wdrnib5b8d2cni9gvans7kkf1sh9nk-zoxide-0.9.8/bin/zoxide init fish --cmd cd | source

    if test "$TERM" != dumb
        /nix/store/7zimgz51bybh58bgdb7366kjfww93c4r-starship-1.23.0/bin/starship init fish | source

    end

    /nix/store/wpw5h6sdfda0gh53p58az2mrk6d8l6px-pay-respects-0.7.9/bin/pay-respects fish --alias | source

    function __fish_command_not_found_handler --on-event fish_command_not_found
        /nix/store/8iyfp59vsrrkba875y01im3j1hmhnrpw-command-not-found $argv
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/evolve/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/3by7b7afc50p6v1khzj7wyml1rdmagff-direnv-2.37.1/bin/direnv hook fish | source

end
