# vim:ft=kitty

## name: Clair-Obscur Light

# The basic colors
foreground              #000000
background              #ffffff
selection_foreground    #ffffff
selection_background    #000000

# Cursor colors
cursor                  #000000
cursor_text_color       #ffffff

# kitty window border colors
active_border_color     #000000
inactive_border_color   #d0d0d0

# Tab bar colors
active_tab_foreground   #000000
active_tab_background   #e8e8e8
inactive_tab_foreground #888888
inactive_tab_background #f5f5f5

# The basic 16 colors
# black
color0 #000000
color8 #555555

# red
color1  #cc3333
color9  #aa1111

# green
color2  #447744
color10 #336633

# yellow
color3  #997722
color11 #775511

# blue
color4  #335588
color12 #224477

# magenta
color5  #774477
color13 #553355

# cyan
color6  #336677
color14 #225566

# white
color7  #eeeeee
color15 #ffffff
